### ISSUE TITLE
Atividades p/ Ana Vitória - Primeiro Projeto

### ISSUE THREAD

**Issue by ulissesdifreitas** [ulissesdifreitas/Ajax_Test#4]
# Para Ana Vitória:

- [x] 01 - criar um arquivo chamado "testeCadastroUsuario.spec.js" na pasta /cypress/integration
- [x] 02 - acessar o site "demoqa"
- [x] 03 - clicar no menu "Elements"
- [x] 04 - selecionar a aba "web tables"
- [x]  05 - clicar no botão "ADD"
- [x] 06 - realizar cadastro de novo usuário

**Comment by anavitorianog** [comment]
Atividade Concluída!

**Comment by anavitorianog** [comment]
Atividade concluída, pull request finalizado!
